pipeline {
    agent any
    tools { maven 'Maven3'; jdk 'JDK22' }
    environment {
        DOCKER_HUB_USER = "thefruss032"
        IMAGE_NAME = "peminjaman-service"
        REGISTRY_CREDS = "docker-hub-creds"
    }
    stages {
        stage('CI/CD Process') {
            steps {
                ws("F:/Jenkins/workspace/${IMAGE_NAME}") {
                    checkout scm
                    dir('peminjaman') {
                        bat 'mvn clean package -DskipTests'
                        script {
                            bat "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} ."
                            withCredentials([usernamePassword(credentialsId: REGISTRY_CREDS, passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                                bat "docker login -u %USER% -p %PASS%"
                                bat "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER}"
                            }
                        }
                    }
                    bat "kubectl set image deployment/peminjaman-app peminjaman=${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} -n perpustakaan-ns"
                    bat "kubectl rollout status deployment/peminjaman-app -n perpustakaan-ns"
                }
            }
        }
    }
}