pipeline {
    agent any
    tools { maven 'Maven3'; jdk 'JDK22' }
    environment {
        DOCKER_HUB_USER = "thefruss032"
        IMAGE_NAME = "buku-service"
        REGISTRY_CREDS = "docker-hub-creds"
    }
    stages {
        stage('1. Setup Workspace & Checkout') {
            steps {
                ws("F:/Jenkins/workspace/${IMAGE_NAME}") {
                    checkout scm
                    echo "Workspace set to F:/Jenkins/workspace/${IMAGE_NAME}"
                    
                    dir('buku') {
                        echo '2. Building JAR...'
                        bat 'mvn clean package -DskipTests'
                        
                        echo '3. Building & Pushing Docker Image...'
                        script {
                            bat "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} ."
                            
                            withCredentials([usernamePassword(credentialsId: REGISTRY_CREDS, passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                                bat "docker login -u %USER% -p %PASS%"
                                bat "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER}"
                                bat "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest"
                            }
                        }
                    }
                    
                    echo '4. Deploying to Kubernetes...'
                    bat "kubectl set image deployment/buku-app buku=${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} -n perpustakaan-ns"
                    bat "kubectl rollout status deployment/buku-app -n perpustakaan-ns"
                }
            }
        }
    }
}
